# GoReleaser configuration for LazyOC
version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: lazyoc
    main: ./cmd/lazyoc
    binary: lazyoc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip 32-bit builds and some combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: lazyoc
    builds:
      - lazyoc
    name_template: >-
      lazyoc_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

# Homebrew formula (CLI tool) - Disabled until token is configured
# brews:
#   - name: lazyoc
#     homepage: "https://github.com/katyella/lazyoc"
#     description: "A lazy terminal UI for OpenShift/Kubernetes clusters"
#     license: "Apache-2.0"
#     repository:
#       owner: katyella
#       name: homebrew-tap
#     directory: Formula
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
#     install: |
#       bin.install "lazyoc"
#     test: |
#       system "#{bin}/lazyoc --version"

# Windows Scoop (disabled until repository is created)
# scoops:
#   - name: lazyoc
#     homepage: "https://github.com/katyella/lazyoc"
#     description: "A lazy terminal UI for OpenShift/Kubernetes clusters"
#     license: "Apache-2.0"
#     repository:
#       owner: katyella
#       name: scoop-bucket

release:
  github:
    owner: katyella
    name: lazyoc
  draft: false
  mode: append
  header: |
    ## LazyOC {{ .Tag }}
    
    Welcome to this new release of LazyOC! 🎉
    
    ### Installation
    
    #### From Source
    ```bash
    go install github.com/katyella/lazyoc/cmd/lazyoc@latest
    ```
    
    #### Manual Installation
    
    Download the appropriate binary from the assets below and extract:
    
    **Linux (x86_64)**
    ```bash
    curl -L https://github.com/katyella/lazyoc/releases/download/{{ .Tag }}/lazyoc_{{ .Version }}_Linux_x86_64.tar.gz | tar xz
    sudo mv lazyoc /usr/local/bin/
    ```
    
    **macOS (x86_64)**
    ```bash
    curl -L https://github.com/katyella/lazyoc/releases/download/{{ .Tag }}/lazyoc_{{ .Version }}_Darwin_x86_64.tar.gz | tar xz
    sudo mv lazyoc /usr/local/bin/
    ```
    
    **macOS (ARM64)**
    ```bash
    curl -L https://github.com/katyella/lazyoc/releases/download/{{ .Tag }}/lazyoc_{{ .Version }}_Darwin_arm64.tar.gz | tar xz
    sudo mv lazyoc /usr/local/bin/
    ```
  footer: |
    **Full Changelog**: https://github.com/katyella/lazyoc/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    Thanks to all contributors! 🙏